version: 3
jobs:
  build:
    docker:
      - image: cimg/php:7.4.30-node
      - image: cimg/postgres:11.17
        environment:
          POSTGRES_DB: catchApp
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: catchApp
      DB_USERNAME: default
      DB_PASSWORD: secret
    steps:
      - checkout
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: get ready for postgres
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: php test
          # command: php artisan test
          command: vendor/bin/phpunit tests/Feature
  deploy:
    docker:
      - image: cimg/php:7.4.30-node
    steps:
      - add_ssh_keys
      - run:
          name: first_deploy
          command: |
            ssh -o StrictHostKeyChecking=no -t suna-aws@${FIRST_EC2} "cd catchApp && \
              git pull origin master && \
              composer install -n --no-dev --prefer-dist && \
              npm ci && \
              npm run prod && \
              php artisan migrate --force && \
              php artisan config:cache"
      - run:
          name: second_deploy
          command: |
            ssh -o StrictHostKeyChecking=no -t suna-aws@${SECOND_EC2} "cd catchApp && \
              git pull origin master && \
              composer install -n --no-dev --prefer-dist && \
              npm ci && \
              npm run prod && \
              php artisan migrate --force && \
              php artisan config:cache"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master